[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd mindlaw-landing && npm ci']

[phases.build]
cmds = ['cd mindlaw-landing && npm run build']

[start]
cmd = 'cd mindlaw-landing && npm start'
